name: Continuous integration
on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: sudo apt-get update -y && sudo apt-get install libwayland-dev libwebkitgtk rust-gtk-sys-devel libproxy-webkitgtk4 webkitgtk4 libsoup libsoup-devel webkitgtk4-devel libprotobuf-dev gcc-multilib clang libclang-dev protobuf-compiler -y
      - name: Test
      - run: cargo test --all
      - name: Format
      - run: cargo fmt --all -- --check
      - name: Clippy
      - run: cargo clippy --all -- -D warnings